### ISSUE TITLE
About removal or replacement of samples

### ISSUE THREAD

**Issue by Sti2nd** [LMMS/assets#13]
Not for pack 1, but in the future, to further raise the quality of the samples.

The beats and bassloopes in LMMS are little used / only used by a few. Removing them could then save some space and wouldn't affect so many projects. I reckon one could write a script for the lsp which finds out what samples are the least common, and then we would know how many a removal would have an impact on.

However I can see that the beats and bassloopes can be useful for beginners, so I propose remaking the ones with the lowest quality. All of those is in the "beats" folder.
break03.ogg
electro_beat02.ogg
rave_hihat01.ogg
rave_hihat02.ogg
rave_kick01.ogg
rave_snare01.ogg

**Comment by WrillicR** [comment]
Closing this to perhaps be reopened in a discussion of legacy samples.
