### ISSUE TITLE
Short vocal samples form unfa

### ISSUE THREAD

**Issue by unfa** [LMMS/assets#16]
Sorry if this is not the place to post them, I wasn't active in this project for long time.

I'd release them under CC0 for LMMS (they are licensed CC-BY on Freesound):

Here's my latest recording:
http://freesound.org/people/unfa/sounds/270301/

And here's more accumulated over the years:
http://freesound.org/people/unfa/packs/9633/

**Comment by Umcaruje** [comment]
Could you pick out the samples you think will contibute best to the sample pack and make a PR where you add them to a `Unsorted samples/unfa short vocals` folder. That'd help a lot.

P.S. Sorry for the late response.

**Comment by Sawuare** [comment]
@unfa @Umcaruje (in case you're not subscribed to this issue).

I picked 5 samples from http://freesound.org/people/unfa/sounds/270301/ and edited them by downsampling, normalizing, and fading the ends. They are here: [unfa vocals.zip](https://github.com/LMMS/assets/files/6565143/unfa.vocals.zip). They would be the first vocal samples in the library.

Let me know what you think of them and if I used suitable words to describe them.

**Comment by Sawuare** [comment]
I noticed some low noise in the samples so I filtered it out.
I added the samples in https://github.com/LMMS/assets/commit/1687d2ea58d1be9ed577a2dd0ed477f1887a808f. Closing.
