### ISSUE TITLE
Kitchen Samples

### ISSUE THREAD

**Issue by Spekular** [LMMS/assets#17]
[This was posted recently on /r/edmproduction](https://www.reddit.com/r/edmproduction/comments/3lh4t0/free_kitchen_sounds_sample_pack/)

The author states that "You're free to use these sounds however you'd like except for repackaging them in a paid sample pack, everything else is fair game!". Of course we should definitely still ask since including them in a DAW is a pretty big deal, but what do you think?

**Comment by Spekular** [comment]
[Same guy has just posted water sounds as well](https://www.reddit.com/r/edmproduction/comments/3m8mpm/im_back_with_more_free_samples_this_time_all/)

**Comment by SirBothersome** [comment]
@Spekular We need basic drums at the moment. Ambient/niche samples are not high-priority.

**Comment by tresf** [comment]
> except for repackaging them in a paid sample pack

That breaks CC0, so they're a no go anyway.

**Comment by Spekular** [comment]
Actually, we could have some fairly niche samples as part of the proposed lmms.io sample packs. If this is desired I could contact the author about changing his license.
