### ISSUE TITLE
Bundling GSi Soundfonts

### ISSUE THREAD

**Issue by tresf** [LMMS/assets#18]
If any of these are worthy of bundling, I have in writing from the author that they can all be released CC0.

> _Guido Scognamiglio zioguido@gmail.com
> Nov. 30th 2015, 12:11 PM Eastern_
> 
> Hi,
> I am the author of those soundfonts. I made them between 1998 and 2001 and the Creative Commons license was not even a known concept back then. Do what you want with them, I just don't have time to bother with that old stuff.  Sorry for not being more helpful.
>  - Guido.
> 
> ... Speaking of licensing, l wish only to inform you about something you
> should be careful about:
> 
> **`E-15_Piano.zip`** -> This was sampled out of a Roland E-15
> **`HammondC3.zip`** -> "Hammond" and "C3" are registered trademarks
> **`i5s_organs.zip`** -> the sounds included in this soundfont were sampled from a Korg i5s
> **`M3Rorgans.zip`** -> these came from a Korg M3R
> **`M3Rpads.zip`** -> ditto
> **`Rhodes.zip`** -> Rhodes is a registered trademark
> **`RobyTamaDrums.zip`** -> Tama is a registered trademark
> **`TamaRockSTAR.zip`** -> ditto
> **`Universe.zip`** -> this uses the name of a preset of the Korg M1 from which this sound was sampled

http://www.genuinesoundware.com/?a=soundfonts
1. What can we do legally with the sounds he warns about? (just skip them perhaps?)
2. Are they worth it? @Umcaruje @mikobuntu @Spekular @musikbear if any of you have the time to sanity check these that would be great.
3. Fundamentally, @michaelgregorius @Wallacoloo (anyone above or anyone not watching this repo) any objections in bundling some SF2's?

**Comment by Spekular** [comment]
I've tested a few (the one's without issues minus RealAcousticDrums) and they all seem to work well and sound good. There are a few inconsistencies though. Some kits, like gold drums, have different sounds on every key in their range. Others, like tamburo, have a few blank notes. Also, gold drums, premier drum kit, and tamburo all have two separate banks with one patch each. The patches have different names but sound the same.

Anyway, here are the ranges for anyone who wants to do more thorough testing (I hope I'm labelling them correctly. I'm assuming two white notes down from C2 is A1)

* Gold Drums: A1 - B3
* Hard Rock Drums: B1 - C4
* Melotti Drums: B1 - B3
* New Drums: B1 - C4
* Premier Drum Kit: B1 - G3
* Tamburo: B1 - G3

**Comment by Wallacoloo** [comment]
I have no objection to bundling these if everyone's happy with the quality.
Iirc the lmms downloads sit around 40 mb, so we can afford to package some
more sounds. Thanks, @Spekular, for doing some testing.

**Comment by tresf** [comment]
> two white notes down from C2 is A1

Wouldn't that make it A2?

> The patches have different names but sound the same.

Possible.  There's a chance that they are slightly different recordings which have been offered as a humanization option.  I'd make sure they aren't slight variations before removing duplicates.  There are free soundfont editors (such as [polyphone](http://www.polyphone.fr/index.php?lang=en&page=download)) that can make the removal and cleanup process trivial.  

> Some kits, like gold drums, have different sounds on every key in their range. 

This isn't uncommon.  Percussion doesn't follow the same note rules as tone instruments, so the soundfont author chooses to implement in their own way.  Generally speaking, a [standard MIDI mapping is used](https://upload.wikimedia.org/wikipedia/commons/8/85/GMStandardDrumMap.gif) which corresponds with the typical MIDI drumkit.   I have a homemade maraca soundfont which is just sixteen recordings of a maraca on 16 consecutive notes. 

And remember, CC0 allows us to modify these though, so keep that in mind before we accept some into our codebase.

**Comment by Spekular** [comment]
@tresf

When I said "different sounds on each note" I just meant the opposite of
"some notes had no sound". In hindsight, just "sounds on each note" would
have been clearer.

As for the range, the A note below C3 still belongs to the octave below, so
it should be A2, no? From Wikipedia on "Piano Key frequencies"

>"the 49th key, *the fifth A (called A4)*, tuned to 440 Hz (referred to as
A440 <https://en.m.wikipedia.org/wiki/A440_(pitch_standard)>)"

Under the heading "List" is an image[1]  showing:

>"An 88-key piano, with the octaves numbered and Middle C
<https://en.m.wikipedia.org/wiki/C_(musical_note)#Middle_C> (cyan) and A440
<https://en.m.wikipedia.org/wiki/A440_(pitch_standard)> (yellow)
highlighted"

where C4 is below A440 (which I think is A4).

[1](https://commons.m.wikimedia.org/wiki/File:Piano_Frequencies.svg)

**Comment by musikBear** [comment]
I have just dl the first one **e-15-piano.zip** so i do that one now on win32, / just fyi :) 
I will add my findings here in this comment, and add the test-file.mmp to LSP, too.

**Comment by michaelgregorius** [comment]
Is it possible to host soundfonts on LSP? If that's the case I'd propose to add them there and perhaps provide a link to LSP in the "Help" menu.

Once the soundfonts are officially distributed with LMMS this creates some kind of obligation to keep them for backwards compatibility.

I have to admit though that I do not use soundfonts when making music but rather stick to synths. :) Also I wasn't able to check the quality of the soundfonts due to the same reason that @musikBear mentioned.

**Comment by tresf** [comment]
> I have just dl the first one e-15-piano.zip so i do that one now on win32, / just fyi :) 
I will add my findings here in this comment, and add the test-file.mmp to LSP, too.
Well thats was 'simple' The format is sfArk. I have no software that can handle that. -sorry
The others has format 'sfpack'. Again i do not have software to handle it.
@tresf -sorry.

Then convert them using a [sfark -> sf2 utility](https://cloudconvert.com/sfark-to-sf2).

> Once the soundfonts are officially distributed with LMMS this creates some kind of obligation to keep them for backwards compatibility.

Sure, but you could make the same argument for any sample we bundle.  They aren't immune to change, just need to be decided carefully.  The status I'd like to change is the fact that we don't bundle ANY sf2s now and changing that has its pros and cons... pros and cons which I'd like to continue discussion about.

>  I have to admit though that I do not use soundfonts when making music but rather stick to synths.

Well, many VST plugins are glorified soundfonts... many drum plugins are just samples with some envelope and reverb settings.

Sorry to plug my own music here, but if you listen to "Speck Of Dust" from BoL V1, you'll hear a track which makes heavy use of soundfonts, particularly the string instruments, which cannot yet be simulated using a pure software synth.

**Comment by tresf** [comment]
> Is it possible to host soundfonts on LSP?

We don't have sf2 upload support enabled.  We can add via the database if we categorize it correctly.  Here's the function which checks for a valid file extension... 

https://github.com/LMMS/lmms.io/blob/master/public/lsp/dbo.php#L389

**Comment by michaelgregorius** [comment]
> Then convert them using a sfark -> sf2 utility.

Thanks for the link! I was searching for online tools to convert but that link did not show up.

> The status I'd like to change is the fact that we don't bundle ANY sf2s now and changing that has its pros and cons... pros and cons which I'd like to continue discussion about.

I agree that if there is an SF2 player then some content that can be used with it would be good to have as well.

> Well, many VST plugins are glorified soundfonts... many drum plugins are just samples with some envelope and reverb settings.

It depends on the VSTs. The classic ones like Synth1, Charlatan, Spire, Harmor, Zebra, Sylenth1, etc. should all use "real" synthesis.

> particularly the string instruments, which cannot yet be simulated using a pure software synth.

While we are a bit off topic, it again depends on the synth being used. This example which I find quite expressive uses no samples but just additive synthesis:
https://www.youtube.com/watch?feature=player_detailpage&v=X8cBZzNEh_o#t=266

**Comment by tresf** [comment]
> it again depends on the synth being used

I'd argue it depends on the sound you're looking to achieve.  I used the term "string instruments" because a violin (for example) really doesn't have an authentic synthetic version... but nearly all tone instruments in generally cannot be synthesized to the humanized recording.  Piano, trumpet, violin, if you compare the patch instrument to their synthetic counter parts, there's a huge difference and one sounds synthetic (while also full and unique) when the other sounds more organic.

This isn't to say it's impossible, there are expensive synths out there that do a fine job at synthesizing instruments, but to serve as a replacement to the patch bank would assume it's contextually equivalent, which in my experience -- albeit biased -- is seldom the case.  When I find an exception... a synth that replicates the sound of a sound bank, it tends to have a sound bank inside it anyway. :)

> While we are a bit off topic

I'd argue that it is quite on-topic since we're discussing the value of including soundfonts, which is weighted on real-life use cases.

**Comment by tresf** [comment]
> As for the range, the A note below C3 still belongs to the octave below, so it should be A2, no?

Yes, you are correct (I'm wrong).  Thanks.

**Comment by musikBear** [comment]
> Then convert them using a sfark -> sf2 utility.

That was a bookmark in a NY moment - Thanks!

**Comment by WrillicR** [comment]
The public domain GSi Soundfonts have been extracted to samples, a selection of which has been edited and committed in 6da8ecb. Closing.
