### ISSUE TITLE
Replacements for .ds files?

### ISSUE THREAD

**Issue by SirBothersome** [LMMS/assets#24]
So I'm about 90% finished with a new acoustic library, and I've got a fairly decent amount of source material for the Electro Library. Since the essentials are coming close to being covered, I was wondering. Was there any interest in replacing the plethora of random/weird/useless-but-fun/esoteric .ds sound files with similar content? I don't want to waste any time making stuff we don't need. Thanks

**Comment by DeRobyJ** [comment]
Actually I use those .ds files in a lot of projects, and replacing them would break those projects, I'd have to manually replace them :(

**Comment by tresf** [comment]
> replacing .ds sound files with similar content?

Depends what you mean by "similar".  If the samples are of equal length and similar sound, we can write an upgrade script.

Undoubtedly at some point we have to break backwards compatibility, but the strategy for doing so must be carefully thought of.  Making thousands of tracks in our LSP instantly become unplayable is a bit of a problem and offering a sample pack downloads would be a lot easier if we employed an installation technique that unburdened the user from this task.

For example, if we add a new file extension `.sspz` -- a new hypothetical sample pack archive format --  to LMMS (and register the file association with LMMS) we could have a process which imports the sample pack into `LMMS WORKING DIRECTORY` configured in the DAW and allows a smoother transition to a brand new internal library.

Then we can update the code on our LSP and also within LMMS to warn when old projects borrow from a dated sample pack, etc.

**Comment by SirBothersome** [comment]
Thanks for the welcome! I'll see what I can do

**Comment by SirBothersome** [comment]
> For example, if we add a new file extension .sspz -- a new hypothetical sample pack archive format -- to LMMS (and register the file association with the OS to auto-open with LMMS) we could have a process which imports the sample pack into LMMS WORKING DIRECTORY configured in the DAW and allows a smoother transition to a brand new internal library.

Then we can update the code on our LSP and also within LMMS to warn when old projects borrow from a dated sample pack, etc.

I like that idea, 

> Depends what you mean by "similar".

By similar, I originally meant, "found sounds", niche samples, and other kooky sounds, but I do think I could replicate some of the .ds sounds

**Comment by SirBothersome** [comment]
Closing. This can be discussed on discord.
