### ISSUE TITLE
Copyright in mhak Kick metadata

### ISSUE THREAD

**Issue by SirBothersome** [LMMS/assets#26]
So while I was putting the mhak kicks back in the repo, I noticed this
![mhak](https://cloud.githubusercontent.com/assets/20342439/21242918/a4537170-c2e4-11e6-93e1-bff4c352017d.PNG)
Now, I know he let us use it cc0 and all, but this kinda looks bad. Scrubbing the metadata is a cinch, but I wanted to ask before I did. Do we even want these?

**Comment by Umcaruje** [comment]
He didn't let us use CC0. That's the whole point of all the conversations. There was a problem in the communication that was never fixed. Please read the threads carefully. His kicks are a blessing, but the licensing needs to get sorted and only several kicks should be picked.

**Comment by SirBothersome** [comment]
>He didn't let us use CC0

Ah, my bad for assuming. Yet I somehow remember cc0 being mentioned in @HDDigitizerMusic 's invite email. I think it was Digitizer's promise of credit that defeated the cc0, not Hakala's consent, or lack thereof.
At any rate, I have a VST that can poop out kicks of similar quality in a matter of seconds.
***dashes off to evil lair***

**Comment by SirBothersome** [comment]
Okay, so after reading though [#1018](urlhttps://github.com/LMMS/lmms/search?q=1018&type=Issues&utf8=%E2%9C%93) it appears that HDD _implied_ that Hakalas consented to cc0. Haven't found any factual evidence though.

**Comment by tresf** [comment]
> I think it was Digitizer's promise of credit that defeated the cc0, not Hakala's consent, or lack thereof.

Correct.

**Comment by SirBothersome** [comment]
Closing, no longer applicable, mhak's kicks are not in the repo anymore
