### ISSUE TITLE
Some Wontolla Drums may not be cc0 eligible.

### ISSUE THREAD

**Issue by SirBothersome** [LMMS/assets#28]
So, in the process of watching tuts to improve my sound design, I stumbled across this one
https://www.youtube.com/watch?v=eDHOCLCUjv8 which happens to be by Wontolla. In the video, Wontolla uses a drum bundled with FL Studio to make a snare sample. Wontolla has told me that he factually knows his kicks are purely from scratch 
![wontollamail](https://cloud.githubusercontent.com/assets/20342439/21318025/8b399f40-c5d5-11e6-9403-6db3dead5fdb.PNG)
but this definitely makes the rights to the snare samples shaky in my opinion. Should we still include them?

**Comment by tresf** [comment]
@SirBothersome this is a concern of mine as a whole.  It's nice for content authors to state their work is `CC0`, but we need to know also that their work itself it eligible.  I'm not sure how the other DAWs handle this.  If we can use a commercial synth to create a `CC0` sample, where do we draw the line?

I think ideally, every sample we ship should be recorded by one of us or synthesized with FOSS.

**Comment by tresf** [comment]
@SirBothersome on a side-note to you and others, please coordinate with @Umcaruje on communication to artists from this point forward to avoid redundant questions or confusion to the content authors.

**Comment by SirBothersome** [comment]
>  If we can use a commercial synth to create a CC0 sample, where do we draw the line?
@tresf, not sure where the conflict here is. Any person can sell a song with a non-demo version of a commercial synth. Nothing in any VST EULA that I've read restricts what sort of licensing you can put on your end product. Meanwhile, many, many sample makers stipulate that you cannot redistribute their samples, even modified ones. 
>I think ideally, every sample we ship should be recorded by one of us or synthesized with FOSS. This is pragmatic and probably not practical at all though. :/

What I'm working one sir, not as difficult as it seems. re; #25

**Comment by tresf** [comment]
> Meanwhile, many, many sample makers stipulate that you cannot redistribute their samples, even modified ones.

Right, but you seem to be describing a DSP sound generator whereas many plugins are simply a DLL wrapper around a bunch of potentially licensed sample files.  We just need to be wise and precise about what artists are allowed to call their own creative works.

**Comment by SirBothersome** [comment]
> whereas many plugins are simply a DLL wrapper around a bunch of potentially licensed sample files

@tresf, ah yes, a very tricky threat that I quickly discovered. I make sure to be very thorough on reading about how the VST's I use function.Fortunately, vsts such as Hinton and Fairchild's BIGROOMKICKSYNTH operate on pure synthesis.

**Comment by Umcaruje** [comment]
I asked Wontolla about this, the only sample that was made from another sample is `snare-artemis-v2.wav`. That one should be removed. The rest are made from scratch.

**Comment by SirBothersome** [comment]
> That one should be removed.

@Umcaruje , Done, see #29

**Comment by SirBothersome** [comment]
Closing, has been resolved
