### ISSUE TITLE
We should not promise credit for cc0 samples

### ISSUE THREAD

**Issue by SirBothersome** [LMMS/assets#35]
@Hussam-Eddin-Alhomsi I noticed this ~~change~~ to our readme 
![nono hussam](https://user-images.githubusercontent.com/20342439/28367819-4a932786-6c60-11e7-8bd7-ef1037da4104.PNG)

Please do not offer credit for cc0 samples as this has greatly complicated matters in the past.
https://github.com/LMMS/lmms/issues/1589
@tresf, @Umcaruje,  while this is a voluntary offer, I still deleted the credit offer to be sure, if I'm wrong, please let me know.

**Comment by Hussam-Eddin-Alhomsi** [comment]
This isn't a new change that was introduced with my last big commit.
The samples are licensed under CC0, we can give credit or not, however, since this is an open-source project and the number of contributers isn't limited, I think we shouldn't offer credit.

**Comment by SirBothersome** [comment]
@Hussam-Eddin-Alhomsi I apologize for attributing the offer to you then... I had seen your recentlcommit and thought you put it there. My mistake.

**Comment by Hussam-Eddin-Alhomsi** [comment]
@SirBothersome It's OK. 🙂
