### ISSUE TITLE
Sample projects not in Fedora package

### ISSUE THREAD

**Issue by ideaman924** [LMMS/assets#39]
There's no sample projects in Fedora's package.

How to reproduce:

sudo dnf install lmms

Is this intentional to save space? How do I get these sample projects?

**Comment by liushuyu** [comment]
1. Wrong tracker
2. Please report this incident to Fedora. This is packaging problem, not the problem of LMMS

**Comment by liushuyu** [comment]
Will mark this as `invalid` and closed if no relevant information is provided later.

**Comment by ideaman924** [comment]
Will do, thank you.

Marking this as closed.
